-- CONSULTA PERSONALIZADA: INTENCIONES CANALES UNIDAS 1 4
--A nivel superficial, este query construye una base consolidada de intenciones de cancelación/retiro de clientes de servicios fijos, 
--enriqueciendo cada intención con información de ofertas de retención, fallas de servicio y reincidencias históricas. 
--Finalmente intenta dejar una fila principal por intención.


--i.ID_SERVICIO = o.SUBSCRIBER_ID

;
SELECT *,

 ROW_NUMBER() OVER (
            PARTITION BY ID_UNICO
            ORDER BY
              FECHA_cREACION DESC
        ) AS FILTRO_FINAL

FROM (SELECT *
FROM (SELECT *,
CASE
    WHEN TIPO_INCIDENCIAS IS NOT NULL THEN TIPO_INCIDENCIAS
    WHEN TIPO_INCIDENCIAS IS NULL AND NIVELES_POTENCIA IS NOT NULL THEN 'Niveles de Potencia'
    WHEN CATEGORIZACION_OPERACIONAL_N3 IN (
        'Falla en el servicio - Imputables a claro',
        'Fallas en el servicio imputables al cliente'
    ) THEN 'Clientes Silenciosos'
    ELSE 'No tiene fallas'
END AS FALLAS_SERVICIO
FROM (
SELECT *
FROM (
    SELECT
        i.*,
        --b.*, 
		NIVELES_POTENCIA.*, incidencias.*,
        o.*,
        /* Seguro FINAL: 1 fila por intención, priorizando:
           - Última oferta del mes (fecha activación SUP desc)
           - Primera baja posterior a la intención (fecha baja asc; nulos al final)
        */
        ROW_NUMBER() OVER (
            PARTITION BY i.ID_UNICO
            ORDER BY
              DATE(o.FECHA_ACTIVACION_SUP) DESC,
              --CASE WHEN b.FB IS NULL THEN DATE '2999-12-31' ELSE DATE(b.FB) END ASC,
              o.ID_DETALLE_PLAN DESC
        ) AS rn_final
    FROM (
        /* ================= INTENCIONES_FINALES ================= */
        SELECT t1.*, 'PRIMERA LINEA' AS TIPO,
               ROW_NUMBER() OVER (ORDER BY FECHA_IMPACTO ASC) AS ID_UNICO
        FROM (
            SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1
        ) t1
    ) i

    /* ================= OFERTAS_SUPLEMENTARIAS (deduplicado) ================= */
    LEFT JOIN (
        SELECT 
            p.SUBSCRIBER_ID,
            p.FECHA_ACTIVACION_SUP,
            p.FECHA_MES_ACT,
            p.ID_DETALLE_PLAN,
            p.HERRAMIENTA_RETENCION,
            p.TECNOLOGIA_HOMOLOGADA2,
            p.ID_IDENTIFICACION_HOMOLOGADA,
            p.ID_IDENTIFICACION_GRUPO,
            p.CICLO_FINAL,
            u.CANAL_OFERTA,
            ci.F_IMPACTO
        FROM (
            /* --- Última oferta del mes por SUBSCRIBER_ID --- */
            SELECT 
                R.SUBSCRIBER_ID,
                DATE(R.FECHA_ACTIVACION_SUP) AS FECHA_ACTIVACION_SUP,
                TO_CHAR(DATE(R.FECHA_ACTIVACION_SUP),'YYYYMM') AS FECHA_MES_ACT,
                R.ID_DETALLE_PLAN,
                R.NUM_SERVICIOS,
                /* Homologaciones y mapeos */
                CASE                   
                    WHEN SUBPRODUCTO_HOMOLOGADO = 'Television'  AND TECNOLOGIA = 'DTH' THEN 'TV DTH'
                    ELSE SUBPRODUCTO_HOMOLOGADO 
                END AS SUBPRODUCTO_HOMOLOGADO_2,
                CASE 
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 26-25 ','CICLO 26-25 ','Ciclo Completo ' ,'CICLO FMC DIA 26-25 ',
                                        'CICLO DIA 26 FECHA MAX PAGO DIA 08 PROXIMO MES ') THEN 'CICLO FMC DIA 26-25'
                    WHEN DESC_CICLO IN ('CICLO 11-10 ', 'CICLO FMC DIA 11-10 ', 'Ciclo 2 Mensual ','Ciclo Datos Autoconsumo ','Ciclo 2 ',
                                        'CICLO FMC DIA 11-10 ','CICLO FMC DIA 11-10 ','CICLO DIA 11 FECHA MAX PAGO DIA 23 ') THEN 'CICLO FMC DIA 11-10'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 24-23 ','CICLO 23-24 ','CICLO FMC DIA 24-23 ' ,'CICLO FMC DIA 24-23 ',
                                        'CICLO DIA 24 FECHA MAX PAGO DIA 06 PROXIMO MES ') THEN 'CICLO FMC DIA 24-23'
                    WHEN DESC_CICLO IN ('CICLO DIA 2-1 ','CICLO FMC DIA 2-1 ','CICLO FMC DIA 2-1 ', 'CICLO DIA 2 FECHA MAX PAGO DIA 14 ' ,'CICLO DIA 2 FECHA MAX PAGO DIA 15 ') THEN 'CICLO FMC DIA 2-1'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 8-7 ','CICLO DIA 8 FECHA MAX PAGO DIA 20 ') THEN 'CICLO FMC DIA 8-7'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 15-14 ','CICLO DIA 15-14 ','CICLO DIA 15 FECHA MAX PAGO DIA 27 ' ,'CICLO DIA 15 FECHA MAX PAGO DIA 26 ') THEN 'CICLO FMC DIA 15-14'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 19-18 ','29 ') THEN 'CICLO FMC DIA 19-18'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 21-20 ','30 ' ) THEN 'CICLO FMC DIA 21-20'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 28-27 ','CICLO FMC DIA 28-27','31 ') THEN 'CICLO FMC DIA 28-27'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 17-16 ', '28 ' ) THEN 'CICLO FMC DIA 17-16'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 13-12 ','27 ' ) THEN 'CICLO FMC DIA 13-12'
                    WHEN DESC_CICLO IN ('CICLO FMC DIA 4-3 ','25 ') THEN 'CICLO FMC DIA 4-3'
                    WHEN DESC_CICLO IN( 'CICLO FMC DIA 6-5 ','26 ') THEN 'CICLO FMC DIA 6-5' 
                    WHEN DESC_CICLO IS NULL THEN 'NA'
                    ELSE '-' 
                END AS CICLO_FINAL,
                CASE
                    WHEN TECNOLOGIA IN ('CLOUD','ADMINISTRADA', 'COBRE', 'FIBRA', 'FIBRA TERCERIZADA', 'HFC','ETHERNET', 'METRO ETHERNET', 'RADIO', 'RADIO LICENCIADA', 'RADIO NO LICENCIADA', 'UM Terceros') THEN 'HFC'
                    WHEN TECNOLOGIA = 'DTH' THEN 'DTH'
                    WHEN TECNOLOGIA IN ('GPON', 'GPON IPTV', 'GPON OTT') THEN 'GPON'
                    ELSE TECNOLOGIA
                END AS TECNOLOGIA_HOMOLOGADA2,
                CASE WHEN ID_IDENTIFICACION= 'CED' THEN 'CEDULA'
                     WHEN ID_IDENTIFICACION= 'PAS' THEN 'PASAPORTE'
                     ELSE ID_IDENTIFICACION
                END AS ID_IDENTIFICACION_HOMOLOGADA,
                CASE WHEN ID_IDENTIFICACION IN ('CED','PAS') THEN 'MASIVO'
                     WHEN ID_IDENTIFICACION = 'RUC' THEN 'CORPORATIVO'
                     ELSE ID_IDENTIFICACION
                END AS ID_IDENTIFICACION_GRUPO,
                CASE
                    WHEN ID_DETALLE_PLAN IN ('100122921','100129923','100129899') THEN '50% dcto 3 meses'
                    WHEN ID_DETALLE_PLAN IN ('100122922','100129925','100129921') THEN '50% dcto 6 meses'
                    WHEN ID_DETALLE_PLAN IN ('100124462','100124428','100124495') THEN 'TB Gratis'
                    WHEN ID_DETALLE_PLAN IN ('54000','100069327','100084514','53999','100064127','54001','100064128') THEN '25% dcto 12 meses'
                    WHEN ID_DETALLE_PLAN IN ('100124611','100124446','100124542') THEN '15% dcto indefinido(clientes Brownfield)'
                    WHEN ID_DETALLE_PLAN IN ('53038','53213','53038','53119','100069284','100084511') THEN '25% dcto 4 meses'
                    WHEN ID_DETALLE_PLAN IN ('53220','53107','53212','53108','53118','100069322','100084513') THEN '25% dcto 6 meses'
                    ELSE ID_DETALLE_PLAN
                END AS HERRAMIENTA_RETENCION,
                ROW_NUMBER() OVER (
                    PARTITION BY R.SUBSCRIBER_ID, TO_CHAR(DATE(R.FECHA_ACTIVACION_SUP),'YYYYMM')
                    ORDER BY DATE(R.FECHA_ACTIVACION_SUP) DESC, R.ID_DETALLE_PLAN DESC
                ) AS rn_mes
            FROM OID_DB.OID_DB.OID_INVENTARIO_FIJO R
            WHERE R.FECHA_ACTIVACION_SUP > '20250630'
              AND R.TIPO_SERVICIO = 'SUPLEMENTARIA'
              AND R.ID_DETALLE_PLAN IN (
                  '51695','53119','53118','54000','54003','53216','51667','74211','74210','74212','74213','68399',
                  '100052869','100052871','100052873','100052875','100052877','100052879','100052921','100052923','100052925','100052927',
                  '100069284','100069322','100069327','100069330','100069334','100069750','100070539','100070643','100070645','100070647',
                  '100070650','100070652','100122921','100129923','100129899','100122922','100129925','100129921','100124462','100124428',
                  '100124495','53999','100064127','54001','100064128','100084514','100124611','100124446','100124542','53038','53213',
                  '53220','53107','53212','53108','53118','100084511','100084513'
              )
        ) p
        LEFT JOIN (
            /* Desduplica tabla de ofertas U */
            SELECT *
            FROM (
                SELECT
                    DATE(FECHA_ACTIVACION) AS FECHA_ACTIVACION,
                    OFFERING_ID,
                    ID_SERVICIO AS ID_SERV,
                    FECHA_INACTIVACION,
                    EMPLOYEE_CODE,
                    EMPLOYEE_NAME,
                    CASE 
                        WHEN POSITION('{"en_US":"' IN OFICINA) > 0 AND POSITION('","es_LA":"' IN OFICINA) > 0 
                            THEN TRIM(BOTH '"' FROM SUBSTRING(OFICINA 
                                FROM POSITION('{"en_US":"' IN OFICINA) + 9 
                                FOR POSITION('","es_LA":"' IN OFICINA) - POSITION('{"en_US":"' IN OFICINA) - 9
                            ))
                        ELSE OFICINA
                    END AS CANAL_OFERTA,
                    ROW_NUMBER() OVER (
                        PARTITION BY ID_SERVICIO, OFFERING_ID, DATE(FECHA_ACTIVACION)
                        ORDER BY FECHA_INACTIVACION DESC, EMPLOYEE_CODE DESC
                    ) AS rn_u
                FROM OID_DB.OID_DB.OID_INVENTARIO_OFERTAS_FIJO
            ) uu
            WHERE uu.rn_u = 1
        ) u
          ON  p.SUBSCRIBER_ID   = u.ID_SERV
          AND p.ID_DETALLE_PLAN = u.OFFERING_ID
          AND DATE(p.FECHA_ACTIVACION_SUP) = u.FECHA_ACTIVACION

        LEFT JOIN (
            /* Desduplica ciclos (por seguridad) */
            SELECT DES_CICLO, FECHA_INICIO, FECHA_FIN, MAX(FECHA_IMPACTO) AS F_IMPACTO
            FROM sandbox.SAC_RET.sac_ciclo_facturacion_fijo
            GROUP BY DES_CICLO, FECHA_INICIO, FECHA_FIN
        ) ci
          ON p.CICLO_FINAL = ci.DES_CICLO
         AND DATE(p.FECHA_ACTIVACION_SUP) BETWEEN ci.FECHA_INICIO AND ci.FECHA_FIN

        WHERE p.rn_mes = 1
    ) o
      ON i.ID_SERVICIO = o.SUBSCRIBER_ID
     AND o.FECHA_MES_ACT = TO_CHAR(DATE(i.FECHA_CREACION),'YYYYMM')
     AND DATE(o.FECHA_ACTIVACION_SUP) >= DATE(i.FECHA_CREACION)

--------------INCIDENCIAS 
	LEFT JOIN (
SELECT 
        CASE 
            WHEN NRO_ORDEN_DE_TRABAJO IS NOT NULL THEN 'Mantenimiento'
            WHEN NRO_ORDEN_DE_TRABAJO IS NULL THEN 'Reclamos'
        END AS TIPO_INCIDENCIAS,
		CASE 
            WHEN TECNOLOGIA_SERV IN ('V.GPON', 'GPON', '.GPON') THEN 'GPON'
            WHEN TECNOLOGIA_SERV IN ('HFC', 'FC') THEN 'HFC' 
            ELSE TECNOLOGIA_SERV 
        END AS TECNOLOGIA_HOMOLOGADA,SERVICIO_SERV,FECHA_INGRESO AS FI,
		CATEGORIZACION_TIER_1, CATEGORIZACION_TIER_2, CATEGORIZACION_TIER_3
		FROM OID_DB.OID_DB.OID_REMEDY_INCIDENTES_SAC WHERE FECHA_INGRESO>='20240101' AND TECNOLOGIA_HOMOLOGADA IN ('HFC', 'GPON')
)INCIDENCIAS  ON I.ID_SERVICIO=INCIDENCIAS.SERVICIO_SERV AND TO_CHAR(INCIDENCIAS.FI, 'YYYYMM') BETWEEN TO_CHAR(ADD_MONTHS(I.FECHA_CREACION, -3), 'YYYYMM')  AND TO_CHAR(I.FECHA_CREACION, 'YYYYMM')

----NIVELES DE POTENCIA

LEFT JOIN (
 SELECT SERVICE_NUMBER, FECHA AS FECHA_NIVELES, 'SI' NIVELES_POTENCIA FROM  SANDBOX.SAC_RET.FIJO_CONSOLIDADO_NIVELES_POTENCIA
)NIVELES_POTENCIA ON NIVELES_POTENCIA.SERVICE_NUMBER=I.ID_SERVICIO 
AND TO_CHAR(NIVELES_POTENCIA.FECHA_NIVELES, 'YYYYMM') BETWEEN TO_CHAR(ADD_MONTHS(I.FECHA_CREACION, -3), 'YYYYMM')  AND TO_CHAR(I.FECHA_CREACION, 'YYYYMM')

) z
WHERE rn_final = 1
)ppp)H_FINAL


LEFT JOIN 
(
SELECT ID_SERVICIO AS SERVICIO_1, FECHA_IMPACTO AS FECHA_IMPACTO1, 'REINCIDENCIA -1' REINCIDENCIA1 FROM (
 SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1)I1
)MES_1  
ON COALESCE(H_FINAL.ID_SERVICIO, '1') = COALESCE(MES_1.SERVICIO_1, '1')
AND  TO_CHAR(MES_1.FECHA_IMPACTO1,'YYYYMM') = TO_CHAR(ADD_MONTHS(H_FINAL.FECHA_IMPACTO, -1), 'YYYYMM') 
AND H_FINAL.FALLAS_SERVICIO NOT IN ('No tiene fallas')


LEFT JOIN 
(
SELECT ID_SERVICIO AS SERVICIO_2, FECHA_IMPACTO AS FECHA_IMPACTO2, 'REINCIDENCIA -2' REINCIDENCIA2 FROM (
 SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1)I1
)MES_2  
ON COALESCE(H_FINAL.ID_SERVICIO, '1') = COALESCE(MES_2.SERVICIO_2, '1')
AND H_FINAL.ID_SERVICIO NOT IN ('1', '0') 
AND  TO_CHAR(MES_2.FECHA_IMPACTO2,'YYYYMM') = TO_CHAR(ADD_MONTHS(H_FINAL.FECHA_IMPACTO, -2), 'YYYYMM') 
AND H_FINAL.FALLAS_SERVICIO NOT IN ('No tiene fallas')


LEFT JOIN 
(
SELECT ID_SERVICIO AS SERVICIO_3, FECHA_IMPACTO AS FECHA_IMPACTO3, 'REINCIDENCIA -3' REINCIDENCIA3 FROM (
 SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1)I1
)MES_3  
ON COALESCE(H_FINAL.ID_SERVICIO, '1') = COALESCE(MES_3.SERVICIO_3, '1')
AND  TO_CHAR(MES_3.FECHA_IMPACTO3,'YYYYMM') = TO_CHAR(ADD_MONTHS(H_FINAL.FECHA_IMPACTO, -3), 'YYYYMM') 
AND H_FINAL.FALLAS_SERVICIO NOT IN ('No tiene fallas')

----------------INTENCIONES REINCIDENCIAS

LEFT JOIN 
(
SELECT ID_SERVICIO AS SERVICIO_INTENCION1, FECHA_IMPACTO AS FECHA_IMPACTOINTENCION1, 'REINCIDENCIA -1' REINCIDENCIAINTENCION1 FROM (
 SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1)I1
)MES_1INTENCION  
ON COALESCE(H_FINAL.ID_SERVICIO, '1') = COALESCE(MES_1INTENCION.SERVICIO_INTENCION1, '1')
AND  TO_CHAR(MES_1INTENCION.FECHA_IMPACTOINTENCION1,'YYYYMM') = TO_CHAR(ADD_MONTHS(H_FINAL.FECHA_IMPACTO, -1), 'YYYYMM') 



LEFT JOIN 
(
SELECT ID_SERVICIO AS SERVICIO_INTENCION2, FECHA_IMPACTO AS FECHA_IMPACTOINTENCION2, 'REINCIDENCIA -2' REINCIDENCIAINTENCION2 FROM (
 SELECT FECHA_ALTA, ID_ORDEN_TRABAJO,'INSTANTCALL' AS CANAL,FECHA_CREACION, ID_SERVICIO, IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NULL AS NFILAF, NULL AS RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INSTANTCALL 
            WHERE CATEGORIA_RESOLUCION_NIVEL_2F <> 'RECHAZADO'

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'KIOSKO' AS CANAL, FECHA_INGRESO, SUBSCRIBER_ID, IDENTIFICACION_CLIENTE, SUBPRODUCTO_HOMOLOGADO_FINAL,TECNOLOGIA_FINAL1,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1, TIPOLOGIA_GESTION,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, NULL AS RNR,NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_KIOSKO 
            WHERE NFILAF = 1

            UNION ALL
            SELECT FECHA_ALTA,ID_ORDEN_TRABAJO,'INBOUND' AS CANAL,FECHA_CREACION, ID_SERVICIO,IDENTIFICACION, FAMILIA_FINAL,TECNOLOGIA_FINAL,CATEGORIZACION_OPERACIONAL_N1,CATEGORIZACION_OPERACIONAL_N2, CATEGORIZACION_OPERACIONAL_N3,
                   REGION,CATEGORIA_RESOLUCION_NIVEL_1,CATEGORIA_RESOLUCION_NIVEL_2_F,CATEGORIA_RESOLUCION_NIVEL_3,FECHA_IMPACTO,NFILAF, 
                   CASE 
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RRSS','CONTACT CENTER') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) NOT IN ('RECHAZADO') THEN 1
                       WHEN UPPER(GRUPO_SOPORTE_ASIGNADOF) IN ('RETENCIÓN Y RECUPERACIÓN') AND UPPER(CATEGORIA_RESOLUCION_NIVEL_2_F) IN ('NO RETENIDO', 'RETENIDO') THEN 1
                   END AS RNR,
                   GRUPO_SOPORTE_ASIGNADOF
            FROM sandbox.SAC_RET.FIJO_INTENCIONES_INBOUND 
            WHERE RNR = 1 AND NFILAF = 1

            UNION ALL
            SELECT  FECHA_ALTA,NULL AS ID_ORDEN_TRABAJO,'BARRA' AS CANAL,FECHA AS FECHA_CREACION,SUBSCRIBER_FINAL AS ID_SERVICIO,IDENTIFICACION, SUBPRODUCTO_HOMOLOGADO_FF AS FAMILIA_FINAL,TECNOLOGIA_FINAL_F AS TECNOLOGIA_FINAL,SUB_CATEGORIA_VALIDA AS CATEGORIZACION_OPERACIONAL_N1,
                    NULL AS CATEGORIZACION_OPERACIONAL_N2,NULL AS CATEGORIZACION_OPERACIONAL_N3,
                    REGION,NULL AS CATEGORIA_RESOLUCION_NIVEL_1,NULL AS CATEGORIA_RESOLUCION_NIVEL_2F,NULL AS CATEGORIA_RESOLUCION_NIVEL_3,
                    TO_DATE(MES_IMPACTO, 'YYYYMM') AS FECHA_IMPACTO,NFILAFF AS NFILAF, RNR, NULL AS GRUPO_SOPORTE_ASIGNADOF
            FROM SANDBOX.SAC_RET.FIJO_INTENCION_BARRA 
            WHERE RNR = 1 AND TECNOLOGIA_FINAL_F IN ('HFC','GPON') AND NFILAFF = 1)I1
)MES_2INTENCION   
ON COALESCE(H_FINAL.ID_SERVICIO, '1') = COALESCE(MES_2INTENCION.SERVICIO_INTENCION2, '1')
AND H_FINAL.ID_SERVICIO NOT IN ('1', '0') 
AND  TO_CHAR(MES_2INTENCION.FECHA_IMPACTOINTENCION2,'YYYYMM') = TO_CHAR(ADD_MONTHS(H_FINAL.FECHA_IMPACTO, -2), 'YYYYMM') 

)FINALES_F
;